### ISSUE TITLE
`v1.0.0` Checklist

### ISSUE THREAD

**Issue by hyperupcall** [hyperupcall/bash-core#8]
With `v1.0.0` coming around the corner, there are a few tasks required

- [ ] Remove deprecated functions
  - `core.init()`
  - `core.stacktrace_print()`
  - etc.

- [x] Deprecate error handling functions

- [ ] Remove error handling functions
 
- [x] Determine if functions like `should_output_color` and `get_package_info` should live here. It seems the should be somewhere else (like `bash-utils`)
	- Yes, such functions have been deprecated here and moved to [bash-std](https://github.com/hyperupcall/bash-std)
